project_name: wowforge-cli
builds:
  - dir: .
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X "main.version=v{{ trimprefix .Version "v" }}"
archives:
  - format: tar.gz
    wrap_in_directory: false
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
      - "^ci"
brews:
  - name: wowforge-cli
    repository:
      owner: m-triassi
      name: homebrew-public
    homepage: "https://github.com/m-triassi/wowforge-cli"
    description: "Easily add and update addons for your World of Warcraft installation"
    license: "MIT"
nfpms:
  - package_name: wowforge-cli
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: m-triassi
    homepage: https://github.com/m-triassi/wowforge-cli
    description: |-
      Easily add and update addons for your World of Warcraft installation
    license: MIT
    maintainer: Massimo Triassi <contact@triassi.ca>
    formats:
      - deb
      - apk
      - rpm
      - archlinux
    dependencies:
      - git