name: Generate release-artifacts

on:
  push:
    branches: ["main"]

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set-up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.3'
          cache: true
          cache-dependency-path: go.sum

      - name: Tag commit
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: git tag ${{ steps.changelog.outputs.tag }}

      - name: Push changelog
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          git push origin master

      - name: Release new CLI version
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}